### ISSUE TITLE
Compatible Plate & Case

### ISSUE THREAD

**Issue by dedisuryadi** [friction07/corne-xiao#1]
So, I've been thinking about building a Corne xiao. But before I take the plunge, I want to ask about the compatible plates and case. The plate should be compatible with this release [corne-cherry-v2.1.0](https://github.com/foostan/crkbd/releases/tag/corne-cherry-v2.1.0), right? Also, do you have any recommendations for a wireless 3D-printed case? Does this case, [Corne Wireless Void Case with better access](https://www.printables.com/model/689497-corne-wireless-void-case-with-better-access), look okay to you in terms of compatibility? Really cool project; I very much appreciate what you've done here. Thank you!

**Comment by viktorvasylen** [comment]
Hi there,
I've built my Corne xiao with this [case](https://www.printables.com/de/model/347524-corne-keyboard-case-5-and-6-columns), a variant with 600mah batteries. Seems like your case is based on mine or vice-versa. So it should be compatible.
I mounted on-off switches in TRRS holes. It is not that attractive but useful, the button is handy and it works just fine for me 

![20240503_092204](https://github.com/friction07/corne-xiao/assets/85550885/adfa0bc3-d488-4806-9ee6-f07f8fe1e495)
![20240503_092227](https://github.com/friction07/corne-xiao/assets/85550885/57fdbecc-56ee-477b-843b-388a2311bf28)
![20240503_092239](https://github.com/friction07/corne-xiao/assets/85550885/bc41e712-19d1-4e37-8a99-7a4bbebb082a)

**Comment by dedisuryadi** [comment]
The battery, red cables and on/off switch make it looks like will not pass airport checkpoint security, love it. Thank you for the link, I will make one.

**Comment by friction07** [comment]
I shared files for the case I personally use @dedisuryadi.

**Comment by dedisuryadi** [comment]
> I shared files for the case I personally use @dedisuryadi.

Thank you. I already build one using void 600 mah stl, only problem with that case is I need to push the mcu a little bit when plugging a cable, a detachable magnetic cable should solve it.


![20240603_112206](https://github.com/friction07/corne-xiao/assets/6575619/5ff25c66-130b-4fff-97f9-43527ba70b30)



![20240603_112238](https://github.com/friction07/corne-xiao/assets/6575619/4693a32d-0f38-4d3e-8239-37398a29f2c4)


![20240603_112919](https://github.com/friction07/corne-xiao/assets/6575619/6d1bfea6-b3ef-46c5-84f4-a3d4f60af471)

**Comment by viktorvasylen** [comment]
@dedisuryadi I have used a file to remove excess material and make the hole bigger

**Comment by dedisuryadi** [comment]
@viktorvasylen Yes, thank you. Less work than cut it open completely
