### ISSUE TITLE
More infos

### ISSUE THREAD

**Issue by k0mpreni** [friction07/corne-xiao#4]
Hey, love the project and will order some pcb for it.

I have a few questions:
- Do you maybe have pictures of where and how the battery is soldered?
- Do you recommend any battery capacity?
- Is it compatible with low profile Choc keys?

Thanks!

**Comment by friction07** [comment]
Hi, I am glad this project was helpful.

- I have placed the battery underneath the PCB. I use the modified chieftain case which has a cavity of 55x31mm and you can fit a 4mm thick battery within these dimensions  ( STL files are available in the "case" folder ). The size of the battery will depend on the case you use. Check out the "Compatible Plate & Case" issue which has some pictures for reference.

- You should be fine with anything over 100mah. I personally use 400mah batteries.

- It's not compatible with choc keycaps.

**Comment by k0mpreni** [comment]
Awesome thanks for the infos!
